### PR TITLE
Fix #1365 - issue with checking hub site while doing hub to hub association

### LINKED ISSUE #1365: [BUG] Add-PnPHubToHubAssociation silently fails if target is not registered as a hub site
### Reporting an Issue or Missing Feature
Using the Add-PnPHubToHubAssociation command silently fails if the target specified is not registered as a hub site. Behaviour is the same as if both source and target are registered as hub sites and the connection succeeds.

### Expected behavior 
An error message if the target is not registered as a hub site.

### Actual behavior 
Command completes with no reported output, however as the target is not registered as a hub site, no connection is made.
Site is registered as a hub site, SiteB is not:
image

### Steps to reproduce behavior

1. Create Communication site 'SiteA'.
2. Register SiteA as a hub site.
3. Create Communication site 'SiteB'
4. Use the following PnP PowerShell commands to attempt to associate the sites:
`Connect-PnPOnline`
`Add-PnPHubToHubAssociation -SourceUrl https://tenant.sharepoint.com/sites/SiteA -TargetUrl https://tenant.sharepoint.com/sites/SiteB`

### What is the version of the Cmdlet module you are running?
1.8.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

### PR DESCRIPTION
**Pull request by gautamdsheth**
## Type ##
- [x] Bug Fix
- [ ] New Feature
- [ ] Sample

## Related Issues? ##
Fixes #1365 

## What is in this Pull Request ? ##
Throw error in Hub to hub association if both sites are not hub sites.

### CODE REVIEW

File: src/Commands/Admin/AddHubToHubAssociation.cs [hunk 1]
```diff
@@ -33,22 +33,57 @@ protected override void ExecuteCmdlet()
...
             else
             {
-                HubSiteProperties sourceProperties = this.Tenant.GetHubSitePropertiesByUrl(SourceUrl);
-                ClientContext.Load(sourceProperties);
-                var targetSite = this.Tenant.GetSiteByUrl(TargetUrl);
-                ClientContext.Load(targetSite);
-                ClientContext.ExecuteQueryRetry();
-                sourceProperties.ParentHubSiteId = targetSite.HubSiteId;
-                sourceProperties.Update();
+                ClientObjectList<HubSiteProperties> hubSitesProperties = Tenant.GetHubSitesProperties();
```
Comment (KoenZomers) [inline src/Commands/Admin/AddHubToHubAssociation.cs:44]: Consider changing to checking the HubSiteId property on the tenantsite object instead of retrieving all hub sites.

Comment (gautamdsheth) [reply src/Commands/Admin/AddHubToHubAssociation.cs]: Fixed this , thanks for spotting it
